x-default: &default
  restart: 'always'
  logging:
    driver: 'local'
    options:
      max-size: '50m'
      max-file: '10'

services:
  caddy:
    <<: *default
    image: 'caddy:2'
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - './data/caddy/config/.env'
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile'
      - './data/caddy/data:/data'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:2019/config/']
      interval: '30s'
      timeout: '5s'
      retries: '3'
      start_period: '10s'

  registry:
    <<: *default
    image: 'registry:3'
    env_file:
      - './data/registry/config/.env'
    volumes:
      - './data/registry/data:/var/lib/registry'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:5000/v2/']
      interval: '30s'
      timeout: '5s'
      retries: '3'
      start_period: '10s'
