language: generic

services: docker

cache:
  timeout: 900
  directories:
    - $HOME/cache

env:
{{ENV}}

install:
  - source bin/setup-env
  - images prepare $DOCKER_IMAGES

script:
  - images build $DOCKER_IMAGES

after_success:
  - images push $DOCKER_IMAGES

notifications:
  email:
    on_success: never
    on_failure: never
